<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_More</name>
   <tag></tag>
   <elementGuidId>02586d26-9086-464c-94a3-2dadc2d3441d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rc-link-button[@id='more-link']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>619b87c5-a261-402c-a6af-7e6256d021bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-small</value>
      <webElementGuid>62e2434b-edd9-4741-84f0-470cba90210d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>e1d014e6-c7ee-4b07-aab9-6b3948c644e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;more-link&quot;)/button[1]/span[@class=&quot;text-small&quot;]</value>
      <webElementGuid>91eb50fe-c252-468c-9100-048ccf7420b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rc-link-button[@id='more-link']/button/span</value>
      <webElementGuid>a1bcd007-7ba5-4d30-9cd8-15c3101d7610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP Properties'])[1]/following::span[1]</value>
      <webElementGuid>db46193c-66e8-4cae-8f9f-07ebaf240e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R550'])[1]/following::span[2]</value>
      <webElementGuid>cfaf62b1-6c33-4741-91dd-328419dd2466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venue:'])[1]/preceding::span[1]</value>
      <webElementGuid>8c2ac369-f38c-4ef2-b4d7-2b80369bab9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My-Venue'])[1]/preceding::span[1]</value>
      <webElementGuid>6078fec8-7872-4752-a688-2c46162e5229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='More']/parent::*</value>
      <webElementGuid>d8be68dc-3e8e-45bb-bbbe-9c5ec9c9fb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/rc-link-button/button/span</value>
      <webElementGuid>91a72406-b293-47cc-b97c-d05eff46c72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'More' or . = 'More')]</value>
      <webElementGuid>f6e4b581-e3ec-4f33-b5ea-b7f4f0f45033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
