<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Execute Feature</name>
   <tag></tag>
   <elementGuidId>7c740def-e4c6-4ac5-9eff-5020fcbdad56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myModalLabel2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='myModalLabel2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>4bf241f7-1888-4a5f-8978-81818348b1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>8888d6a6-1110-4c0b-bfac-d5e046ceaa24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myModalLabel2</value>
      <webElementGuid>f7554149-347b-4666-bc42-df271e827842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Execute Feature</value>
      <webElementGuid>1eddc633-fc07-4331-8ccc-2725e48a4584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nav-md modal-open&quot;]/div[@class=&quot;container body&quot;]/div[@class=&quot;main_container&quot;]/div[@class=&quot;right_col&quot;]/div[@class=&quot;modal fade execute-group-modal in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h4[@id=&quot;myModalLabel2&quot;]</value>
      <webElementGuid>b9eb8351-33f6-4585-aacb-31d43f1b376c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='myModalLabel2']</value>
      <webElementGuid>3b19f19d-f2d3-4bc4-98e7-bbc822574982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 5 of 5 entries'])[1]/following::h4[1]</value>
      <webElementGuid>60ac1098-e742-4c1b-a382-6650885f746c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Result'])[5]/following::h4[1]</value>
      <webElementGuid>f91c9468-2f55-46ad-bfa1-dbe4aee10460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::h4[1]</value>
      <webElementGuid>ac7107b3-6b4e-464a-99ac-a285dafd90f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment Variables'])[1]/preceding::h4[1]</value>
      <webElementGuid>26534f85-27b8-4dfa-9ebf-0cdd041dba90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Execute Feature']/parent::*</value>
      <webElementGuid>5b8d5790-e741-41c2-aad6-81c3448b5ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/h4</value>
      <webElementGuid>52bd915c-6f59-4925-ae52-ceb796be1dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'myModalLabel2' and (text() = 'Execute Feature' or . = 'Execute Feature')]</value>
      <webElementGuid>b2d9566a-df83-4089-8aea-37c04a19372b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
