<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Execution Target_exe_target</name>
   <tag></tag>
   <elementGuidId>0bf8e625-daca-416f-bcbb-b64d1c8a8b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gke</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gke']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cea6d66e-59d8-4f88-a7a2-f6dddc8cd5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4f8f363a-6ae8-4012-8487-5ca445ed0c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enable_live()</value>
      <webElementGuid>581b0b36-94f3-42b1-b4d8-3a20d6ab672e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gke</value>
      <webElementGuid>a92c3009-9e59-4681-97b4-8ca2911656d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exe_target</value>
      <webElementGuid>a3e2075e-7f30-4616-b7fa-2b6a0350445f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>G</value>
      <webElementGuid>81fba336-6591-478f-aa9b-a420b1b8a242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gke&quot;)</value>
      <webElementGuid>88159c87-09f6-4721-881d-8dbac85bd8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gke']</value>
      <webElementGuid>873a95ba-e75d-4365-a5d6-02daad933808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exe_GKE_block']/input</value>
      <webElementGuid>3ff815c6-5f94-46dd-876d-a80e8c3866fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>bee958ec-23be-4bae-89ac-303f8d481427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'gke' and @name = 'exe_target']</value>
      <webElementGuid>04324590-36a6-437f-8768-acc0ae5c484d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
