<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Execution Type_exe_type</name>
   <tag></tag>
   <elementGuidId>8552bac5-1882-4504-a706-53aed519c299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sequence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sequence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31d3e3b8-8ffd-435c-bac5-9b7c55acf5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2237c7af-097f-472e-bff4-7db10c9c0712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sequence</value>
      <webElementGuid>a6ea011e-0536-4688-b7d9-8549d40d2ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exe_type</value>
      <webElementGuid>0644b19b-48ca-4948-93a1-3874737ffca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>868fafc3-8727-482c-b099-74e1a912d477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sequence&quot;)</value>
      <webElementGuid>c4d60e7d-52c2-4e2b-ad99-2ea503542bbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sequence']</value>
      <webElementGuid>ac6a1d7f-d086-43b6-838c-01537c66e676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='execution_type']/div/input</value>
      <webElementGuid>3af81058-15b4-433d-b439-15e3f9ead3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>39cd9902-8ed7-4fbd-87a5-7fb861b19b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'sequence' and @name = 'exe_type']</value>
      <webElementGuid>a908540b-2958-41e3-a2d1-0e52d4dd722e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
