<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Live Execution_live-execution</name>
   <tag></tag>
   <elementGuidId>fe0fe437-4f2f-41bd-b53d-c9498298376c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#live-execution</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='live-execution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>182633a2-83f0-40ce-bdf9-4f5ab442856d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>32b162fa-e157-499d-bf3c-750a4c43bbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>live-execution</value>
      <webElementGuid>ff5e335b-393d-4924-8960-0ab8861f7a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>live-execution</value>
      <webElementGuid>8499fa2a-0697-4998-b6b4-f3fe3044f0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;live-execution&quot;)</value>
      <webElementGuid>30fbf555-b571-4b4d-962d-d87fdfd05a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='live-execution']</value>
      <webElementGuid>cb12d0c5-54d6-4e27-a230-d81db6534fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='executeGroupForm']/div[6]/div/input</value>
      <webElementGuid>c41ac9ea-6254-4dd4-9b48-9ed2ec232055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>70818e56-ffb0-4979-aefe-c45c242b6e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'live-execution' and @name = 'live-execution']</value>
      <webElementGuid>dab31c5a-9ccd-496f-8488-b41fc4826d5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
