<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AP_mgmt_R550_functionalites_lab.robot_632e6d</name>
   <tag></tag>
   <elementGuidId>36bc453e-90e3-4379-abd3-65e98363e26d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Execute'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4966b7ba-bc8d-4583-8229-e4c2ac03fffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn  btn-primary btn-xs</value>
      <webElementGuid>ef27d122-550e-44a8-a7f8-9894e90308ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6aaaf9fe-4a48-4ce6-8931-e6590c64fe1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Execute</value>
      <webElementGuid>26c963a5-df43-4d1b-b43e-70181b49879a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>trigger_group_model(85, 'AP_mgmt_Testing_2022Q1Beta')</value>
      <webElementGuid>65e03b70-a489-40d0-969e-c7854468c1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nav-md&quot;]/div[@class=&quot;container body&quot;]/div[@class=&quot;main_container&quot;]/div[@class=&quot;right_col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-sm-8   col-xs-12&quot;]/div[@class=&quot;x_panel&quot;]/div[@class=&quot;x_content&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[4]/div[1]/a[1]/form[1]/input[@class=&quot;btn  btn-primary btn-xs&quot;]</value>
      <webElementGuid>0d838eb5-8ebb-4050-aa50-04b1b39f0e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Execute'])[2]</value>
      <webElementGuid>02858a73-9d39-46c8-9499-9e91618210a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/a/form/input[2]</value>
      <webElementGuid>82fdc197-3645-42f0-936d-f3b7fd9df5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>976c7dfb-de93-46e8-804a-2d812c340f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
