<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Succeeded</name>
   <tag></tag>
   <elementGuidId>d1aecc09-a4cd-49b0-87cf-2ccc781289db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.badge</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;test_stats&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/span[@class=&quot;badge&quot;][count(. | //*[(text() = 'Succeeded' or . = 'Succeeded')]) = count(//*[(text() = 'Succeeded' or . = 'Succeeded')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='test_stats']/tbody/tr/td[9]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ff0c0cd-0f91-4811-a61b-9c871ec9f416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge</value>
      <webElementGuid>31898488-7a07-4da6-8596-5a687c8e1f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Succeeded</value>
      <webElementGuid>587ffef2-f4a9-49a6-a843-e5d542e2fe08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test_stats&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/span[@class=&quot;badge&quot;]</value>
      <webElementGuid>f175b731-66a0-40c0-ab7f-5109761606be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='test_stats']/tbody/tr/td[9]/span</value>
      <webElementGuid>54ad5777-d9a0-4fbe-ab4b-8830dc34ff3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP_mgmt_R550_functionalites_lab'])[1]/following::span[1]</value>
      <webElementGuid>5e5e9b15-87b8-464a-934a-3045429a3c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP_mgmt_R550_functionalites_lab_clone'])[1]/following::span[1]</value>
      <webElementGuid>019215c9-67fb-48c8-8ee2-81276e1c8f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[1]</value>
      <webElementGuid>17a309e1-790b-469f-a69e-12e777393c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May. 01, 2022, 00:55 AM'])[1]/preceding::span[1]</value>
      <webElementGuid>dee0b51f-0bf4-47b1-a437-98ec098ac94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Succeeded']/parent::*</value>
      <webElementGuid>2bdae6ba-f1f2-40f1-9591-49dff0c0518e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/span</value>
      <webElementGuid>fa8b6c43-79dc-464c-826f-17e7e4bca7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Succeeded' or . = 'Succeeded')]</value>
      <webElementGuid>8aef9b34-4238-4f26-a467-d287e1604afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
