<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Succeeded</name>
   <tag></tag>
   <elementGuidId>d1aecc09-a4cd-49b0-87cf-2ccc781289db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.badge</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;test_stats&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/span[@class=&quot;badge&quot;][count(. | //*[(text() = 'Succeeded' or . = 'Succeeded')]) = count(//*[(text() = 'Succeeded' or . = 'Succeeded')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='test_stats']/tbody/tr/td[9]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32e9d449-d546-4b3d-ad90-210e3ea677eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge</value>
      <webElementGuid>a61ca1e0-308f-46e6-9182-5c5cc59d2783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Succeeded</value>
      <webElementGuid>4b0604b9-4306-43e9-a234-93251ba045f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test_stats&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/span[@class=&quot;badge&quot;]</value>
      <webElementGuid>6d0b95a1-74c5-444f-a982-b82b260716b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='test_stats']/tbody/tr/td[9]/span</value>
      <webElementGuid>f153ad69-a512-4683-af7e-58b2eeac0ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP_mgmt_R550_functionalites_lab'])[1]/following::span[1]</value>
      <webElementGuid>0b02488c-beca-46d7-b341-d0eb860b8595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP_mgmt_R550_functionalites_lab_clone'])[1]/following::span[1]</value>
      <webElementGuid>6ec2f977-3aff-476a-aa26-b5387695e2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[1]</value>
      <webElementGuid>059e11ca-4668-482e-9123-aebe70f99a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May. 01, 2022, 00:55 AM'])[1]/preceding::span[1]</value>
      <webElementGuid>cc6e845f-cd62-4623-9ce8-2d048449e9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Succeeded']/parent::*</value>
      <webElementGuid>1c8f6a2e-03b4-4ddc-8f13-f105abbc1079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/span</value>
      <webElementGuid>940075fc-5080-487b-a9de-41a55f629c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Succeeded' or . = 'Succeeded')]</value>
      <webElementGuid>68681f98-de1e-4927-9d5d-5eda262ae4db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
