<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AP_mgmt_Testing_2022Q1Beta</name>
   <tag></tag>
   <elementGuidId>1a7e322c-df5c-4c5a-8127-226b57c7182e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC_Mesh_share_lab1.robot'])[1]/following::td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0e9a5f7f-f928-4f99-bc9e-6a45c193ed37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>5895bf82-4977-4000-b128-3c5617970ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AP_mgmt_Testing_2022Q1Beta</value>
      <webElementGuid>0bef7197-a7b2-4c41-a668-c5be54660ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nav-md&quot;]/div[@class=&quot;container body&quot;]/div[@class=&quot;main_container&quot;]/div[@class=&quot;right_col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-sm-8   col-xs-12&quot;]/div[@class=&quot;x_panel&quot;]/div[@class=&quot;x_content&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>b2d2a184-5528-4d7f-a0e5-3834fb361d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC_Mesh_share_lab1.robot'])[1]/following::td[3]</value>
      <webElementGuid>38e3fb5c-4cdd-4337-98f3-27b9bcf5e77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wlan_Deployment_share_lab1.robot'])[1]/following::td[3]</value>
      <webElementGuid>5a92412d-76f8-4e1b-90d2-43e7e1ebb94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP_mgmt_R510_Functionalites.robot'])[1]/preceding::td[1]</value>
      <webElementGuid>687aa891-d2af-4c8b-bccd-5358ff9405c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP_mgmt_R500_Functionalites.robot'])[1]/preceding::td[1]</value>
      <webElementGuid>22f28c0a-d4ee-40dd-b4de-c96922726bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AP_mgmt_Testing_2022Q1Beta']/parent::*</value>
      <webElementGuid>d87ac1e1-296d-4e67-b941-24b6b814f562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>8e8c2b7b-e7f0-4e5c-89c1-a90d61baf06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AP_mgmt_Testing_2022Q1Beta' or . = 'AP_mgmt_Testing_2022Q1Beta')]</value>
      <webElementGuid>c9561e65-ce77-4002-8eb1-09c4687f207b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
