<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dog Company 1692_icon-user activated</name>
   <tag></tag>
   <elementGuidId>68922b9d-3d27-4806-8a0e-0e0df089ef61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon-user.activated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/rc-root[1]/div[@class=&quot;app-container&quot;]/rc-topbar[1]/div[@class=&quot;topbar-container&quot;]/div[@class=&quot;topbar-right&quot;]/div[@class=&quot;click-boxes ng-star-inserted&quot;]/div[@class=&quot;icon-user activated&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rctooltip</name>
      <type>Main</type>
      <value>User Options</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>delay</name>
      <type>Main</type>
      <value>500</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>bottom</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-user activated</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/rc-root[1]/div[@class=&quot;app-container&quot;]/rc-topbar[1]/div[@class=&quot;topbar-container&quot;]/div[@class=&quot;topbar-right&quot;]/div[@class=&quot;click-boxes ng-star-inserted&quot;]/div[@class=&quot;icon-user activated&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
