<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_An AP Group with that name already exists_a10e3f</name>
   <tag></tag>
   <elementGuidId>09202aa9-c8e4-4144-b486-79d72b2ae308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//rc-validate-indicator[@id='validateIndicator']/div/i[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pi.icon-v.rc-icons-success.ng-star-inserted.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pi icon-v rc-icons-success ng-star-inserted active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validateIndicator&quot;)/div[@class=&quot;validate-indicator ng-star-inserted success&quot;]/i[@class=&quot;pi icon-v rc-icons-success ng-star-inserted active&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rc-validate-indicator[@id='validateIndicator']/div/i[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[3]</value>
   </webElementXpaths>
</WebElementEntity>
