<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__r550_pop_up</name>
   <tag></tag>
   <elementGuidId>e68354f0-4cd7-4195-912b-e26b42520c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_6']/div/p-galleriaitem/div/div/p-galleriaitemslot/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pr_id_6 > div.p-galleria-content > p-galleriaitem > div.p-galleria-item-wrapper > div.p-galleria-item-container > p-galleriaitemslot.p-galleria-item > img.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/qa-alto-file-storage-0/capabilities/wifi/pictures/6.0.0.1.3075/R550.jpg?GoogleAccessId=qa-alto-file-storage@alto-dev-200221.iam.gserviceaccount.com&amp;Expires=1674093742&amp;Signature=hqI3nF5Wn0WQtU+l8xOKV1R1FDrMxzeoUlsfk2CrZME2rRc6dJmJnTu0yHLsKX+uPhTgZkF0gyUOBl1iIgzXlOHNS6wWzvhJ+h0zjirvCFYmShMG0knU96Ljaa5l2FHW%2F63SjY1giER0G4FyDyJIGPLHuF06d1xkFgYXQXMyjOtXBog4Jdl13xE7qplInk2qnl8lxfQpdNpNUXY99wAUji9h3Yy4Ed%2FZJ0t9KbuMkjtPlW6zBkCgPM2dinnR9BO%2FliZid65k4C08qbli8WsZisCn1VRE9uv4fbR7%2FhaSG69Ho2DkzOLZdUOhzMqDycin+xnLEZoh5u0NrilP99naGw%3D%3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_6&quot;)/div[@class=&quot;p-galleria-content&quot;]/p-galleriaitem[1]/div[@class=&quot;p-galleria-item-wrapper&quot;]/div[@class=&quot;p-galleria-item-container&quot;]/p-galleriaitemslot[@class=&quot;p-galleria-item&quot;]/img[@class=&quot;ng-star-inserted&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_6']/div/p-galleriaitem/div/div/p-galleriaitemslot/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://storage.googleapis.com/qa-alto-file-storage-0/capabilities/wifi/pictures/6.0.0.1.3075/R550.jpg?GoogleAccessId=qa-alto-file-storage@alto-dev-200221.iam.gserviceaccount.com&amp;Expires=1674093742&amp;Signature=hqI3nF5Wn0WQtU+l8xOKV1R1FDrMxzeoUlsfk2CrZME2rRc6dJmJnTu0yHLsKX+uPhTgZkF0gyUOBl1iIgzXlOHNS6wWzvhJ+h0zjirvCFYmShMG0knU96Ljaa5l2FHW%2F63SjY1giER0G4FyDyJIGPLHuF06d1xkFgYXQXMyjOtXBog4Jdl13xE7qplInk2qnl8lxfQpdNpNUXY99wAUji9h3Yy4Ed%2FZJ0t9KbuMkjtPlW6zBkCgPM2dinnR9BO%2FliZid65k4C08qbli8WsZisCn1VRE9uv4fbR7%2FhaSG69Ho2DkzOLZdUOhzMqDycin+xnLEZoh5u0NrilP99naGw%3D%3D')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/p-galleria/p-galleriacontent/div/div/p-galleriaitem/div/div/p-galleriaitemslot/img</value>
   </webElementXpaths>
</WebElementEntity>
