<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wi-Fi Clients_ag-9534-input</name>
   <tag></tag>
   <elementGuidId>f2c1123f-f15e-41be-8b39-41994017f428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-9534-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ag-9534-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13a1c52d-3dc5-4048-8e71-f10079fef4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>3d60b2fb-f1a0-4c58-903b-aa46f21ad9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-checkbox-input</value>
      <webElementGuid>ef2fa7f4-9811-44a9-8ec3-eb9c7eaa5c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ede0542e-9b22-4402-83ba-71b11b620f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-9534-input</value>
      <webElementGuid>1bba818e-6c4e-411a-bd2e-c4498c7f310e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Press Space to toggle row selection (unchecked)</value>
      <webElementGuid>dc3de8ab-f297-4681-ba0b-10cd63fb9e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f2764661-17ab-42bf-87e7-3a85043b8f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-9534-input&quot;)</value>
      <webElementGuid>c0df9de3-e059-4ba0-befc-7afec6618b96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-9534-input']</value>
      <webElementGuid>67cf4f4f-12b9-41a5-acf0-2dcfe14fd679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>5eb0b8bf-2b83-46f8-ae85-e0f7c2e3ac4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ag-9534-input']</value>
      <webElementGuid>69ef9aab-5137-444c-8ddb-cda8db4abe86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
