<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wi-Fi Clients_ag-9418-input</name>
   <tag></tag>
   <elementGuidId>62393ca2-6291-4218-8b30-2060eabd28cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-9418-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ag-9418-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df28dc3c-950e-4633-9390-f21c24494d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>5b1e7989-8f6b-4672-b258-d342e0a73768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-checkbox-input</value>
      <webElementGuid>e096d4f6-50ac-4799-bf2d-a89428782184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>87ce0cd2-df16-43c2-8411-e329181ce20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-9418-input</value>
      <webElementGuid>e6e19de6-b053-4b67-8c08-358b1eff763e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Press Space to toggle row selection (unchecked)</value>
      <webElementGuid>d4fafebc-5b4a-4acb-8f0b-c85b994c9fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a4e2bccf-93bf-487d-812a-d7c64a1fda22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-9418-input&quot;)</value>
      <webElementGuid>b3446825-190d-4511-8b3f-c06f6e4f0d3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-9418-input']</value>
      <webElementGuid>cc98a007-d663-4f96-94de-dde74a524f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>f7f3dc4b-ec75-4a98-8f94-d8857e803a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ag-9418-input']</value>
      <webElementGuid>bdb12ded-6f48-48a9-b66f-52eaae414cf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
