<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Type the word , , Delete, ,  t_c20c9b</name>
   <tag></tag>
   <elementGuidId>75662a93-b71e-4d23-bf02-ed649069eb09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deleteText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='deleteText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9896e264-5534-4916-b019-a80a7b1cb24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteText</value>
      <webElementGuid>75e894be-951b-4d6b-8328-37085a7dcdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7966e15-c91f-43b2-a9a5-1c17bdef4cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-m</value>
      <webElementGuid>4da237f9-023e-4cb7-8369-1285ac587c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteText&quot;)</value>
      <webElementGuid>78464a6d-8ea9-4d10-a365-14aa93f77234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='deleteText']</value>
      <webElementGuid>7acb1f57-c846-4f79-b7b2-0d6761b470c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>6dcc638c-b7f7-4d4e-8e4c-6494f4c43bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'deleteText' and @type = 'text']</value>
      <webElementGuid>c982a1d8-eace-4570-9639-de5eeeab397e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
