<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pop_up_r550_pic</name>
   <tag></tag>
   <elementGuidId>d34efa0a-b877-483f-b81e-d41025cd711e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/p-galleria/p-galleriacontent/div/div/p-galleriaitem/div/div/p-galleriaitemslot/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pr_id_17 > div.p-galleria-content > p-galleriaitem > div.p-galleria-item-wrapper > div.p-galleria-item-container > p-galleriaitemslot.p-galleria-item > img.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/qa-alto-file-storage-0/capabilities/wifi/pictures/6.0.0.1.3075/R550.jpg?GoogleAccessId=qa-alto-file-storage@alto-dev-200221.iam.gserviceaccount.com&amp;Expires=1673082340&amp;Signature=LAEZCPvgsMwzbWbMryxDNjMAlWyVg6DUytQ2lqUlHxtGx3eUXLswU2zsmjW05jeujwFlOnYPJYcYrVBeCZk9HkVbgCyKl%2FNyYhriVzvfhciGoqLDBAnwaRdTaQwNQw8LA1JoNLdUzK9hBRQgw9KdSxpVbQXmyiaOrXpZOz6w8HKa%2FlM+bgCvo7s9qsQ24syObSnRZhPke8wd%2Fm%2FrA08%2FMk%2FPvM6wRVCmBlkqLhxhBQPpaN2oeKBV+Y098Gj5BtLMOskwOQXd5%2F+B6ps3yylNxx5fVnCtpsWIGYZRtSSuEjkFlf8yCOICDS3qpCshGsPxvWLR0aA7DYeWxIjPvR6YbA%3D%3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_17&quot;)/div[@class=&quot;p-galleria-content&quot;]/p-galleriaitem[1]/div[@class=&quot;p-galleria-item-wrapper&quot;]/div[@class=&quot;p-galleria-item-container&quot;]/p-galleriaitemslot[@class=&quot;p-galleria-item&quot;]/img[@class=&quot;ng-star-inserted&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_17']/div/p-galleriaitem/div/div/p-galleriaitemslot/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://storage.googleapis.com/qa-alto-file-storage-0/capabilities/wifi/pictures/6.0.0.1.3075/R550.jpg?GoogleAccessId=qa-alto-file-storage@alto-dev-200221.iam.gserviceaccount.com&amp;Expires=1673082340&amp;Signature=LAEZCPvgsMwzbWbMryxDNjMAlWyVg6DUytQ2lqUlHxtGx3eUXLswU2zsmjW05jeujwFlOnYPJYcYrVBeCZk9HkVbgCyKl%2FNyYhriVzvfhciGoqLDBAnwaRdTaQwNQw8LA1JoNLdUzK9hBRQgw9KdSxpVbQXmyiaOrXpZOz6w8HKa%2FlM+bgCvo7s9qsQ24syObSnRZhPke8wd%2Fm%2FrA08%2FMk%2FPvM6wRVCmBlkqLhxhBQPpaN2oeKBV+Y098Gj5BtLMOskwOQXd5%2F+B6ps3yylNxx5fVnCtpsWIGYZRtSSuEjkFlf8yCOICDS3qpCshGsPxvWLR0aA7DYeWxIjPvR6YbA%3D%3D')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/p-galleria/p-galleriacontent/div/div/p-galleriaitem/div/div/p-galleriaitemslot/img</value>
   </webElementXpaths>
</WebElementEntity>
