<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Radio Bands_p-multiselect-trigger-icon ng-tns-c114-21 pi pi-chevron-down</name>
   <tag></tag>
   <elementGuidId>89a0f417-0ec9-4c08-afb6-7ba60a2fd999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-multiselect-trigger-icon.ng-tns-c114-21.pi.pi-chevron-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-multiselect/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9428a672-4a7e-4b71-aef4-8862a7671877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-trigger-icon ng-tns-c114-21 pi pi-chevron-down</value>
      <webElementGuid>9d6c68ae-bf57-4df0-87fa-cbad0f7a706a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/rc-network-ap-group-dialog[1]/rc-dialog[@class=&quot;network-ap-group&quot;]/p-dialog[@class=&quot;popup-dialog ng-tns-c141-20 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c141-20 p-dialog-mask p-component-overlay p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c141-20 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c141-20 p-dialog-content&quot;]/div[@class=&quot;dialog-content ng-tns-c141-20&quot;]/div[@class=&quot;popup-cell&quot;]/div[@class=&quot;radio-container&quot;]/div[@class=&quot;container grey-bg ng-star-inserted&quot;]/div[@class=&quot;field-group-2&quot;]/p-multiselect[@class=&quot;ng-tns-c114-21 ng-untouched ng-pristine ng-valid ng-star-inserted p-inputwrapper-filled p-inputwrapper-focus&quot;]/div[@class=&quot;ng-tns-c114-21 p-multiselect p-component p-multiselect-open p-focus&quot;]/div[@class=&quot;ng-tns-c114-21 p-multiselect-trigger&quot;]/span[@class=&quot;p-multiselect-trigger-icon ng-tns-c114-21 pi pi-chevron-down&quot;]</value>
      <webElementGuid>f6d1143c-7f08-41ee-ac7d-ee6255787512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-multiselect/div/div[3]/span</value>
      <webElementGuid>6a12dbdc-e461-4416-b5e2-3587b01454a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
