<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Radio Bands_p-checkbox-icon_5G</name>
   <tag></tag>
   <elementGuidId>0b7ebfe3-f7df-46c4-97c6-7f2733ed4cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-multiselectitem[2]/li/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6867c3ac-8aa1-4ce3-97b7-7f032e620406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-icon</value>
      <webElementGuid>1e057252-7a47-45a6-8ba3-afe33f8e3db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/rc-network-ap-group-dialog[1]/rc-dialog[@class=&quot;network-ap-group&quot;]/p-dialog[@class=&quot;popup-dialog ng-tns-c141-20 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c141-20 p-dialog-mask p-component-overlay p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c141-20 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c141-20 p-dialog-content&quot;]/div[@class=&quot;dialog-content ng-tns-c141-20&quot;]/div[@class=&quot;popup-cell&quot;]/div[@class=&quot;radio-container&quot;]/div[@class=&quot;container grey-bg ng-star-inserted&quot;]/div[@class=&quot;field-group-2&quot;]/p-multiselect[@class=&quot;ng-tns-c114-21 ng-valid ng-star-inserted p-inputwrapper-filled p-inputwrapper-focus ng-touched ng-dirty&quot;]/div[@class=&quot;ng-tns-c114-21 p-multiselect p-component p-multiselect-open&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c114-21 p-multiselect-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-multiselect-items-wrapper ng-tns-c114-21&quot;]/ul[@class=&quot;p-multiselect-items p-component ng-tns-c114-21&quot;]/p-multiselectitem[@class=&quot;ng-tns-c114-21 ng-star-inserted&quot;]/li[@class=&quot;p-multiselect-item p-ripple&quot;]/div[@class=&quot;p-checkbox p-component&quot;]/div[@class=&quot;p-checkbox-box&quot;]/span[@class=&quot;p-checkbox-icon&quot;]</value>
      <webElementGuid>043352c0-5133-4766-a54c-10f57ff31780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-multiselectitem[2]/li/div/div/span</value>
      <webElementGuid>ff227d2e-ddb0-4859-a233-975ebb30e4ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
