<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Radio Bands_p-checkbox-icon pi pi-check_2_4G</name>
   <tag></tag>
   <elementGuidId>04954066-93f0-47e7-b079-ef7bf274ffb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-checkbox-icon.pi.pi-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e601e847-73e5-4b9e-a532-c8fb1f3d556d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-icon pi pi-check</value>
      <webElementGuid>88809a5b-358a-4cd2-93a9-b42f0dfdf925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/rc-network-ap-group-dialog[1]/rc-dialog[@class=&quot;network-ap-group&quot;]/p-dialog[@class=&quot;popup-dialog ng-tns-c141-20 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c141-20 p-dialog-mask p-component-overlay p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c141-20 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c141-20 p-dialog-content&quot;]/div[@class=&quot;dialog-content ng-tns-c141-20&quot;]/div[@class=&quot;popup-cell&quot;]/div[@class=&quot;radio-container&quot;]/div[@class=&quot;container grey-bg ng-star-inserted&quot;]/div[@class=&quot;field-group-2&quot;]/p-multiselect[@class=&quot;ng-tns-c114-21 ng-valid ng-star-inserted p-inputwrapper-filled p-inputwrapper-focus ng-touched ng-dirty&quot;]/div[@class=&quot;ng-tns-c114-21 p-multiselect p-component p-multiselect-open&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c114-21 p-multiselect-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-multiselect-items-wrapper ng-tns-c114-21&quot;]/ul[@class=&quot;p-multiselect-items p-component ng-tns-c114-21&quot;]/p-multiselectitem[@class=&quot;ng-tns-c114-21 ng-star-inserted&quot;]/li[@class=&quot;p-multiselect-item p-ripple p-highlight&quot;]/div[@class=&quot;p-checkbox p-component&quot;]/div[@class=&quot;p-checkbox-box p-highlight&quot;]/span[@class=&quot;p-checkbox-icon pi pi-check&quot;]</value>
      <webElementGuid>15484382-a50f-4d32-8f2f-cb612988d224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/span</value>
      <webElementGuid>aa9d7ad8-afd1-40c5-ba29-bea13aeba797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
